version: '3.4'

services:
  db:
    environment:
      SA_PASSWORD: 'd1f1cultP@ssw0rd'
      ACCEPT_EULA: "Y"
      
  persons.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Server=db,1433;Database=Epleoo.Persons;User Id=SA;Password=d1f1cultP@ssw0rd;
      - GRPC_PORT=81
    ports:
      - "1650:80"
      - "1651:81"
  pr.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Server=db,1433;Database=Epleoo.PR;User Id=SA;Password=d1f1cultP@ssw0rd;
      - GRPC_PORT=82
    ports:
      - "1656:80"
      - "1657:82"



