version: "3.4"

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment: 
      SA_PASSWORD: 'd1f1cultP@ssw0rd'
      ACCEPT_EULA: "Y"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/data"
  persons.service:
    restart: on-failure:10
    image: "jamesd19/persons.service"
    environment:
      - ConnectionString=Server=db,1433;Database=Persons;User Id=SA;Password=d1f1cultP@ssw0rd;
      - EventBusConnection=rabbitmq
      - GRPC_PORT=81
    ports:
      - "1650:80"
      - "1651:81"
    build:
      context: .
      dockerfile: persons.Dockerfile
    depends_on:
      - rabbitmq
      - db
  pr.service:
    restart: on-failure:10
    image: "jamesd19/pr.service"
    environment:
      - ConnectionString=Server=db,1433;Database=PR;User Id=SA;Password=d1f1cultP@ssw0rd;
      - EventBusConnection=rabbitmq
      - GRPC_PORT=82
    ports:
      - "1656:80"
      - "1657:82"
    build:
      context: .
      dockerfile: pr.Dockerfile
    depends_on:
      - rabbitmq
      - db
volumes:
  rabbitmq_data:
  db:
